Stop global Allwmake if a sub-Allwmake errors

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,6 +1,17 @@
 #!/bin/bash
 cd ${0%/*} || exit 1    # run from this directory
 
+# Stop the script if a command returns an error code
+# trap "exit -1" ERR
+set -e
+trap 'catch $? $LINENO' EXIT
+catch() {
+  if [ "$1" != "0" ]; then
+    # error handling goes here
+    echo "Error $1 occurred on $2"
+  fi
+}
+
 if [ "$PWD" != "$WM_PROJECT_DIR" ]
 then
     echo "Error: Current directory is not \$WM_PROJECT_DIR"
diff --git a/applications/Allwmake b/applications/Allwmake
--- a/applications/Allwmake
+++ b/applications/Allwmake
@@ -1,6 +1,15 @@
 #!/bin/sh
 cd ${0%/*} || exit 1    # run from this directory
 
+set -e
+trap 'catch $? $LINENO' EXIT
+catch() {
+  if [ "$1" != "0" ]; then
+    # error handling goes here
+    echo "Error $1 occurred on $2"
+  fi
+}
+
 if [ "$PWD" != "$WM_PROJECT_DIR/applications" ]
 then
     echo "Error: Current directory in not \$WM_PROJECT_DIR/applications"
